name: AWS Task 8 Automation

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug OIDC claims
        run: |
          python - <<'PY'
          import os
          import urllib.request
          import json
          import base64

          url = os.environ["ACTIONS_ID_TOKEN_REQUEST_URL"]
          token = os.environ["ACTIONS_ID_TOKEN_REQUEST_TOKEN"]

          req = urllib.request.Request(
              url,
              headers={"Authorization": f"bearer {token}"}
          )

          with urllib.request.urlopen(req) as r:
              data = json.load(r)

          jwt = data["value"]
          payload = jwt.split(".")[1]
          payload += "=" * (-len(payload) % 4)

          claims = json.loads(
              base64.urlsafe_b64decode(payload)
          )

          print("aud:", claims.get("aud"))
          print("sub:", claims.get("sub"))
          print("repository:", claims.get("repository"))
          print("ref:", claims.get("ref"))
          print("job_workflow_ref:", claims.get("job_workflow_ref"))
          PY

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::414904928673:role/GitHubActions-Task8-Role
          aws-region: ap-south-1

      - name: Check AWS identity
        run: |
          aws sts get-caller-identity

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AWS automation
        run: |
          python main.py